name: gradebook_mobile
description: GradeBook Mobile - ВІТІ імені Героїв Крут
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^14.6.2

  # Network
  dio: ^5.4.3

  # Auth
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.3           # для PKCE sha256
  url_launcher: ^6.3.1     # відкриває Keycloak у браузері
  app_links: ^6.3.2        # обробляє deep link callback

  # File picker
  file_picker: ^8.0.0

  # UI
  fl_chart: ^0.68.0
  intl: ^0.20.2

  # Localization & utils
  shared_preferences: ^2.3.0
  connectivity_plus: ^6.1.0

  # Notifications
  flutter_local_notifications: ^17.2.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
